export const SHOW_ERROR = 'SHOW_ERROR';
export const RESET_ERROR = 'RESET_ERROR';

export const START_FETCHING = 'START_FETCHING'
export const STOP_FETCHING = 'STOP_FETCHING'

export const CONNECTION_FAILED = 'CONNECTION_FAILED'
export const CONNECTION_SUCCEEDED = 'CONNECTION_SUCCEEDED'

export const RECEIVE_JURISDICTION = 'RECEIVE_JURISDICTION'

export const ADD_VALIDATOR = 'ADD_VALIDATOR';

export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT';

export const VALIDATION_UPDATED = 'VALIDATION_UPDATED';
